id: PA444E331
initial_creation_type: input
source_metadata:
  title: Viṃśatikā vijñaptimātratāsiddhi
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Takamichi Fukita
  contribution to GRETIL: Takamichi Fukita
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:25:35.822083'
last_modified_at: '2022-03-09T15:25:35.822097'
